export const events = [
  {
    slug: "react-conf",
    image: "/images/event1.png",
    title: "React Conf",
    location: "Henderson, Nevada, USA",
    date: "October 7-8, 2025",
    time: "9:00 AM - 5:00 PM",
  },
  {
    slug: "google-io",
    image: "/images/event2.png",
    title: "Google I/O",
    location: "Mountain View, California, USA",
    date: "May 20-21, 2026",
    time: "10:00 AM - 5:00 PM",
  },
  {
    slug: "aws-reinvent",
    image: "/images/event3.png",
    title: "AWS re:Invent",
    location: "Las Vegas, Nevada, USA",
    date: "December 1-5, 2025",
    time: "8:00 AM - 6:00 PM",
  },
  {
    slug: "github-universe",
    image: "/images/event4.png",
    title: "GitHub Universe",
    location: "San Francisco, California, USA",
    date: "October 28-29, 2025",
    time: "9:00 AM - 5:00 PM",
  },
  {
    slug: "kubecon-cloudnativecon",
    image: "/images/event5.png",
    title: "KubeCon + CloudNativeCon",
    location: "Amsterdam, Netherlands",
    date: "April 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "microsoft-build",
    image: "/images/event6.png",
    title: "Microsoft Build",
    location: "Seattle, Washington, USA",
    date: "May 19-21, 2026",
    time: "9:00 AM - 5:00 PM",
  },
];